# Generated by Django 6.0 on 2025-12-19 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_education_degree_alter_education_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_details', to='builder.resume'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='builder.resume'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_details', to='builder.resume'),
        ),
    ]
