# Generated by Django 6.0 on 2025-12-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_certification_resume_alter_project_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='name',
        ),
        migrations.AddField(
            model_name='certification',
            name='date_obtained',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
