# Generated by Django 6.0 on 2025-12-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_alter_certification_resume_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date_obtained',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
